// API client — always fetches static-shape paths under ${BASE_URL}api/.
// In production (static deploy) these are real JSON files generated by
// scripts/build-static.py.
// In dev (vite dev server), Vite proxies /api/* to the FastAPI backend
// (default http://localhost:8000), which serves the same shapes on the fly.

const BASE_PATH = import.meta.env.BASE_URL ?? "/";

export interface TierInfo {
  tier: string;
  title: string;
  lessons: string[];
}

export interface LessonContent {
  tier: string;
  slug: string;
  filename: string;
  content: string;
}

export interface Prerequisite {
  tier: string;
  lesson_num: string;
  description: string;
  slug: string | null;
}

export interface LessonMeta {
  tier: string;
  slug: string;
  title: string;
  prerequisites: Prerequisite[];
  sections: string[];
  strand?: string | null;
  level?: string | null;
  connections?: string[];
  applications?: Array<Record<string, string>>;
}

export interface StrandLevel {
  id: string;
  title: string;
  tier_id: string;
  lessons: string[];
}

export interface StrandInfo {
  id: string;
  title: string;
  description: string;
  levels: StrandLevel[];
}

export async function fetchTiers(): Promise<TierInfo[]> {
  const res = await fetch(`${BASE_PATH}api/tiers.json`);
  if (!res.ok) throw new Error("Failed to fetch tiers");
  return res.json();
}

export async function fetchLesson(
  tier: string,
  slug: string
): Promise<LessonContent> {
  const res = await fetch(`${BASE_PATH}api/tiers/${tier}/${slug}.json`);
  if (!res.ok) throw new Error("Lesson not found");
  return res.json();
}

export async function fetchLessonMeta(
  tier: string,
  slug: string
): Promise<LessonMeta> {
  const res = await fetch(`${BASE_PATH}api/tiers/${tier}/${slug}.meta.json`);
  if (!res.ok) throw new Error("Metadata not found");
  return res.json();
}

export async function fetchStrands(): Promise<StrandInfo[]> {
  const res = await fetch(`${BASE_PATH}api/strands.json`);
  if (!res.ok) throw new Error("Failed to fetch strands");
  return res.json();
}

export async function fetchStrand(id: string): Promise<StrandInfo | null> {
  const all = await fetchStrands();
  return all.find((s) => s.id === id) ?? null;
}
